# Generated by Django 2.1 on 2019-11-23 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=150)),
                ('AuctionStart', models.DateField()),
                ('AuctionEnd', models.DateField()),
                ('CurrentPrice', models.IntegerField()),
                ('HighestBidder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='auctions',
            name='HighestBidder',
        ),
        migrations.RemoveField(
            model_name='auctions',
            name='ItemId',
        ),
        migrations.DeleteModel(
            name='Auctions',
        ),
        migrations.DeleteModel(
            name='Items',
        ),
    ]
