# Generated by Django 2.1 on 2019-11-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_auto_20191123_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='Stats',
            field=models.BooleanField(choices=[(True, 'Open'), (False, 'Close')], default=False),
        ),
    ]
